### ISSUE TITLE
Unsupported value: kotlin.Unit

### ISSUE THREAD

**Issue by ened** [TenkaiRuri/flutter_record#6]
When recording starts with a invalid path, perhaps. 

In any case the "unsupported Value" error should not happen.
```
java.lang.IllegalArgumentException: Unsupported value: kotlin.Unit
	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:289)
	at io.flutter.plugin.common.StandardMethodCodec.encodeErrorEnvelope(StandardMethodCodec.java:70)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error(MethodChannel.java:209)
	at att.moe.flutterrecord.FlutterRecordPlugin.startRecorder(FlutterRecordPlugin.kt:132)
	at att.moe.flutterrecord.FlutterRecordPlugin.onMethodCall(FlutterRecordPlugin.kt:56)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:201)
	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:88)
	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:202)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:326)
	at android.os.Looper.loop(Looper.java:160)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

```

**Comment by rurico** [comment]
I will fix it in the next version.

**Comment by 089apps** [comment]
me too, any idea why this happens? 
Last thing was, I updated my IDE Kotlin Plugin to 1.3.21 (was 1.2.71 before)

**Comment by ened** [comment]
No, but have since then moved to a different pub, called “flutter_sound”.
